<a href="https://colab.research.google.com/github/madhumitha-gv/NLP/blob/main/nlp_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nltk

In [ ]:
paragraph="""
Avul Pakir Jainulabdeen Abdul Kalam was an Indian aerospace scientist and statesman who served as the president of India from 2002 to 2007.

Born and raised in a Muslim family in Rameswaram, Tamil Nadu, Kalam studied physics and aerospace engineering. He spent the next four decades as a scientist and science administrator, mainly at the Defence Research and Development Organisation (DRDO) and Indian Space Research Organisation (ISRO) and was intimately involved in India's civilian space programme and military missile development efforts. He was known as the "Missile Man of India" for his work on the development of ballistic missile and launch vehicle technology. He also played a pivotal organisational, technical, and political role in Pokhran-II nuclear tests in 1998, India's second such test after the first test in 1974.

Kalam was elected as the president of India in 2002 with the support of both the ruling Bharatiya Janata Party and the then-opposition Indian National Congress. He was widely referred to as the "People's President". He engaged in teaching, writing and public service after his presidency. He was a recipient of several awards, including the Bharat Ratna, India's highest civilian honour.

While delivering a lecture at IIM Shillong, Kalam collapsed and died from an apparent cardiac arrest on 27 July 2015, aged 83. Thousands attended the funeral ceremony held in his hometown of Rameswaram, where he was buried with full state honours. A memorial was inaugurated near his home town in 2017.

"""

In [ ]:
paragraph

'\nAvul Pakir Jainulabdeen Abdul Kalam was an Indian aerospace scientist and statesman who served as the president of India from 2002 to 2007.\n\nBorn and raised in a Muslim family in Rameswaram, Tamil Nadu, Kalam studied physics and aerospace engineering. He spent the next four decades as a scientist and science administrator, mainly at the Defence Research and Development Organisation (DRDO) and Indian Space Research Organisation (ISRO) and was intimately involved in India\'s civilian space programme and military missile development efforts. He was known as the "Missile Man of India" for his work on the development of ballistic missile and launch vehicle technology. He also played a pivotal organisational, technical, and political role in Pokhran-II nuclear tests in 1998, India\'s second such test after the first test in 1974.\n\nKalam was elected as the president of India in 2002 with the support of both the ruling Bharatiya Janata Party and the then-opposition Indian National Congr

In [ ]:
!pip install PorterStemmer

  Preparing metadata (setup.py) ... done
  Created wheel for PorterStemmer: filename=PorterStemmer-0.5-cp311-cp311-linux_x86_64.whl size=22567 sha256=876bce439030d57540af07732d25bc0c59c58bd47f9254c156ceb3771b132003
  Stored in directory: /root/.cache/pip/wheels/fd/ab/9e/9e9ffa09a53e5d2ebbf73d6cbe17261232efabcaea580dea97
Successfully built PorterStemmer


In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

## tokenization- converts paragraphs into sentences and into words

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
from nltk.tokenize import sent_tokenize
sentences=nltk.sent_tokenize(paragraph)

In [ ]:
print(sentences)

['\nAvul Pakir Jainulabdeen Abdul Kalam was an Indian aerospace scientist and statesman who served as the president of India from 2002 to 2007.', 'Born and raised in a Muslim family in Rameswaram, Tamil Nadu, Kalam studied physics and aerospace engineering.', "He spent the next four decades as a scientist and science administrator, mainly at the Defence Research and Development Organisation (DRDO) and Indian Space Research Organisation (ISRO) and was intimately involved in India's civilian space programme and military missile development efforts.", 'He was known as the "Missile Man of India" for his work on the development of ballistic missile and launch vehicle technology.', "He also played a pivotal organisational, technical, and political role in Pokhran-II nuclear tests in 1998, India's second such test after the first test in 1974.", 'Kalam was elected as the president of India in 2002 with the support of both the ruling Bharatiya Janata Party and the then-opposition Indian Nation

# Stemming

In [ ]:
stemmer=PorterStemmer()

In [ ]:
stemmer.stem('mainly') # check the stemming of the words

'mainli'

# Lemmatization

In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
lemmatizer=WordNetLemmatizer()

In [ ]:
lemmatizer.lemmatize('goes')

'go'

In [ ]:
import re

In [ ]:

corpus=[]
for i in range(len(sentences)):
  text=re.sub('[^a-zA-Z]',' ',sentences[i])
  text=text.lower()
  corpus.append(text)

In [ ]:
print(corpus)

[' avul pakir jainulabdeen abdul kalam was an indian aerospace scientist and statesman who served as the president of india from      to      ', 'born and raised in a muslim family in rameswaram  tamil nadu  kalam studied physics and aerospace engineering ', 'he spent the next four decades as a scientist and science administrator  mainly at the defence research and development organisation  drdo  and indian space research organisation  isro  and was intimately involved in india s civilian space programme and military missile development efforts ', 'he was known as the  missile man of india  for his work on the development of ballistic missile and launch vehicle technology ', 'he also played a pivotal organisational  technical  and political role in pokhran ii nuclear tests in       india s second such test after the first test in      ', 'kalam was elected as the president of india in      with the support of both the ruling bharatiya janata party and the then opposition indian nationa

In [ ]:
import nltk
nltk.download('stopwords')
stop_words = set(stopwords.words('english')) # Define stop_words here

for sentence in corpus:
    words = nltk.word_tokenize(sentence)   #tokenize
    for word in words:
        if word.lower() not in stop_words:  # remove punctuation/numbers
            print(stemmer.stem(word.lower()))

avul
pakir
jainulabdeen
abdul
kalam
indian
aerospac
scientist
statesman
serv
presid
india
born
rais
muslim
famili
rameswaram
tamil
nadu
kalam
studi
physic
aerospac
engin
spent
next
four
decad
scientist
scienc
administr
mainli
defenc
research
develop
organis
drdo
indian
space
research
organis
isro
intim
involv
india
civilian
space
programm
militari
missil
develop
effort
known
missil
man
india
work
develop
ballist
missil
launch
vehicl
technolog
also
play
pivot
organis
technic
polit
role
pokhran
ii
nuclear
test
india
second
test
first
test
kalam
elect
presid
india
support
rule
bharatiya
janata
parti
opposit
indian
nation
congress
wide
refer
peopl
presid
engag
teach
write
public
servic
presid
recipi
sever
award
includ
bharat
ratna
india
highest
civilian
honour
deliv
lectur
iim
shillong
kalam
collaps
die
appar
cardiac
arrest
juli
age
thousand
attend
funer
ceremoni
held
hometown
rameswaram
buri
full
state
honour
memori
inaugur
near
home
town


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:

for sentence in corpus:
    words = nltk.word_tokenize(sentence)   #tokenize
    for word in words:
        if word.lower() not in stop_words:  # remove punctuation/numbers
            print(lemmatizer.lemmatize(word.lower()))

avul
pakir
jainulabdeen
abdul
kalam
indian
aerospace
scientist
statesman
served
president
india
born
raised
muslim
family
rameswaram
tamil
nadu
kalam
studied
physic
aerospace
engineering
spent
next
four
decade
scientist
science
administrator
mainly
defence
research
development
organisation
drdo
indian
space
research
organisation
isro
intimately
involved
india
civilian
space
programme
military
missile
development
effort
known
missile
man
india
work
development
ballistic
missile
launch
vehicle
technology
also
played
pivotal
organisational
technical
political
role
pokhran
ii
nuclear
test
india
second
test
first
test
kalam
elected
president
india
support
ruling
bharatiya
janata
party
opposition
indian
national
congress
widely
referred
people
president
engaged
teaching
writing
public
service
presidency
recipient
several
award
including
bharat
ratna
india
highest
civilian
honour
delivering
lecture
iim
shillong
kalam
collapsed
died
apparent
cardiac
arrest
july
aged
thousand
attended
funeral
c

# Bag of Words

In [ ]:
## Apply stop words and lemmatization
import re
corpus=[]
for i in range(len(sentences)):
  text=re.sub('[^a-zA-Z]',' ',sentences[i]) # remove extra characters
  text=text.lower()
  text=text.split()
  text=[lemmatizer.lemmatize(word) for word in text if word not in set(stopwords.words('english'))] # lematization for all words except stop words
  text=' '.join(text)
  corpus.append(text)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(binary=True)

In [ ]:
X=cv.fit_transform(corpus).toarray()

In [ ]:
X

array([[1, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X=cv.fit_transform(corpus)

In [ ]:
cv.vocabulary_ # dictionary containing word index mapping

{'avul': 8,
 'pakir': 70,
 'jainulabdeen': 49,
 'abdul': 0,
 'kalam': 52,
 'indian': 45,
 'aerospace': 2,
 'scientist': 91,
 'statesman': 100,
 'served': 93,
 'president': 79,
 'india': 44,
 'born': 13,
 'raised': 82,
 'muslim': 61,
 'family': 30,
 'rameswaram': 83,
 'tamil': 103,
 'nadu': 62,
 'studied': 101,
 'physic': 73,
 'engineering': 29,
 'spent': 98,
 'next': 65,
 'four': 32,
 'decade': 20,
 'science': 90,
 'administrator': 1,
 'mainly': 56,
 'defence': 21,
 'research': 87,
 'development': 23,
 'organisation': 68,
 'drdo': 25,
 'space': 97,
 'isro': 48,
 'intimately': 46,
 'involved': 47,
 'civilian': 17,
 'programme': 80,
 'military': 59,
 'missile': 60,
 'effort': 26,
 'known': 53,
 'man': 57,
 'work': 112,
 'ballistic': 10,
 'launch': 54,
 'vehicle': 110,
 'technology': 106,
 'also': 4,
 'played': 75,
 'pivotal': 74,
 'organisational': 69,
 'technical': 105,
 'political': 77,
 'role': 88,
 'pokhran': 76,
 'ii': 40,
 'nuclear': 66,
 'test': 107,
 'second': 92,
 'first': 31,
 

In [ ]:
corpus[3]

'known missile man india work development ballistic missile launch vehicle technology'

In [ ]:
X[3].toarray().shape

(1, 114)

## N-gram

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True,ngram_range=(3,3))

In [ ]:
X=cv.fit_transform(corpus)

In [ ]:
cv.vocabulary_

{'avul pakir jainulabdeen': 7,
 'pakir jainulabdeen abdul': 74,
 'jainulabdeen abdul kalam': 49,
 'abdul kalam indian': 0,
 'kalam indian aerospace': 53,
 'indian aerospace scientist': 43,
 'aerospace scientist statesman': 2,
 'scientist statesman served': 96,
 'statesman served president': 104,
 'served president india': 98,
 'born raised muslim': 12,
 'raised muslim family': 84,
 'muslim family rameswaram': 65,
 'family rameswaram tamil': 27,
 'rameswaram tamil nadu': 86,
 'tamil nadu kalam': 107,
 'nadu kalam studied': 66,
 'kalam studied physic': 54,
 'studied physic aerospace': 105,
 'physic aerospace engineering': 76,
 'spent next four': 103,
 'next four decade': 68,
 'four decade scientist': 28,
 'decade scientist science': 18,
 'scientist science administrator': 95,
 'science administrator mainly': 94,
 'administrator mainly defence': 1,
 'mainly defence research': 58,
 'defence research development': 19,
 'research development organisation': 90,
 'development organisation drdo

In [ ]:
corpus[0]

'avul pakir jainulabdeen abdul kalam indian aerospace scientist statesman served president india'

In [ ]:
X[0].toarray()

array([[1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

## TFIDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(ngram_range=(3,3), max_features=3)
X=cv.fit_transform(corpus)

In [ ]:
corpus[0]

'avul pakir jainulabdeen abdul kalam indian aerospace scientist statesman served president india'

In [ ]:
X[0].toarray()

array([[0.70710678, 0.        , 0.70710678]])

##Word2vec

In [ ]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 72.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 86.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 14.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatib

In [ ]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api # Import gensim.downloader

wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
vec_king=wv['king']

In [ ]:
wv.most_similar('man')

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
wv.similarity('html','programmer')

0.25811526

In [ ]:
wv.similarity('king','man')

0.22942673

In [ ]:
wv.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]